language: python
python:
  - "3.6"
env:
  - PYTHONPATH=.
install:
  - pip install -r requirements.txt
script:
  - ls -l /home/travis/build/LowellInstruments/Logger
  - ls -l /home/travis/build/LowellInstruments/Logger/tests
  - pytest -v tests
