"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['main.py']
DATA_FILES = ['gui/Calibration Tables', 'gui/designer_files/icons']
OPTIONS = {
    'iconfile': 'gui/designer_files/icons/icon.icns',
    'packages': ['gui','h5py']
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
