# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer_files/options.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        Dialog.setMinimumSize(QtCore.QSize(400, 300))
        Dialog.setMaximumSize(QtCore.QSize(400, 300))
        Dialog.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.checkBox_average_bursts = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_average_bursts.setGeometry(QtCore.QRect(20, 20, 301, 17))
        self.checkBox_average_bursts.setChecked(True)
        self.checkBox_average_bursts.setObjectName("checkBox_average_bursts")
        self.label_2 = QtWidgets.QLabel(self.tab_2)
        self.label_2.setGeometry(QtCore.QRect(20, 50, 271, 20))
        self.label_2.setObjectName("label_2")
        self.radioButton_csv = QtWidgets.QRadioButton(self.tab_2)
        self.radioButton_csv.setGeometry(QtCore.QRect(40, 110, 201, 18))
        self.radioButton_csv.setChecked(True)
        self.radioButton_csv.setObjectName("radioButton_csv")
        self.buttonGroup_output_format = QtWidgets.QButtonGroup(Dialog)
        self.buttonGroup_output_format.setObjectName("buttonGroup_output_format")
        self.buttonGroup_output_format.addButton(self.radioButton_csv)
        self.radioButton_hdf5 = QtWidgets.QRadioButton(self.tab_2)
        self.radioButton_hdf5.setEnabled(True)
        self.radioButton_hdf5.setGeometry(QtCore.QRect(40, 80, 331, 18))
        self.radioButton_hdf5.setObjectName("radioButton_hdf5")
        self.buttonGroup_output_format.addButton(self.radioButton_hdf5)
        self.label = QtWidgets.QLabel(self.tab_2)
        self.label.setGeometry(QtCore.QRect(64, 140, 171, 16))
        self.label.setObjectName("label")
        self.comboBox_split = QtWidgets.QComboBox(self.tab_2)
        self.comboBox_split.setGeometry(QtCore.QRect(64, 170, 211, 22))
        self.comboBox_split.setObjectName("comboBox_split")
        self.comboBox_split.addItem("")
        self.comboBox_split.addItem("")
        self.comboBox_split.addItem("")
        self.comboBox_split.addItem("")
        self.comboBox_split.addItem("")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.radioButton_posix_time = QtWidgets.QRadioButton(self.tab)
        self.radioButton_posix_time.setGeometry(QtCore.QRect(20, 110, 429, 18))
        self.radioButton_posix_time.setObjectName("radioButton_posix_time")
        self.buttonGroup = QtWidgets.QButtonGroup(Dialog)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.radioButton_posix_time)
        self.radioButton_legacy_time = QtWidgets.QRadioButton(self.tab)
        self.radioButton_legacy_time.setGeometry(QtCore.QRect(20, 50, 429, 18))
        self.radioButton_legacy_time.setObjectName("radioButton_legacy_time")
        self.buttonGroup.addButton(self.radioButton_legacy_time)
        self.radioButton_iso8601_time = QtWidgets.QRadioButton(self.tab)
        self.radioButton_iso8601_time.setGeometry(QtCore.QRect(20, 19, 429, 18))
        self.radioButton_iso8601_time.setChecked(True)
        self.radioButton_iso8601_time.setObjectName("radioButton_iso8601_time")
        self.buttonGroup.addButton(self.radioButton_iso8601_time)
        self.radioButton_elapsed_time = QtWidgets.QRadioButton(self.tab)
        self.radioButton_elapsed_time.setGeometry(QtCore.QRect(20, 80, 429, 18))
        self.radioButton_elapsed_time.setObjectName("radioButton_elapsed_time")
        self.buttonGroup.addButton(self.radioButton_elapsed_time)
        self.tabWidget.addTab(self.tab, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.radioButton_factory_cal = QtWidgets.QRadioButton(self.tab_4)
        self.radioButton_factory_cal.setGeometry(QtCore.QRect(20, 20, 331, 17))
        self.radioButton_factory_cal.setChecked(True)
        self.radioButton_factory_cal.setObjectName("radioButton_factory_cal")
        self.buttonGroup_calibration = QtWidgets.QButtonGroup(Dialog)
        self.buttonGroup_calibration.setObjectName("buttonGroup_calibration")
        self.buttonGroup_calibration.addButton(self.radioButton_factory_cal)
        self.radioButton_custom_cal = QtWidgets.QRadioButton(self.tab_4)
        self.radioButton_custom_cal.setGeometry(QtCore.QRect(20, 50, 321, 17))
        self.radioButton_custom_cal.setObjectName("radioButton_custom_cal")
        self.buttonGroup_calibration.addButton(self.radioButton_custom_cal)
        self.lineEdit_custom_cal = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_custom_cal.setEnabled(False)
        self.lineEdit_custom_cal.setGeometry(QtCore.QRect(40, 80, 231, 20))
        self.lineEdit_custom_cal.setReadOnly(True)
        self.lineEdit_custom_cal.setObjectName("lineEdit_custom_cal")
        self.pushButton_browse = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_browse.setEnabled(False)
        self.pushButton_browse.setGeometry(QtCore.QRect(280, 80, 25, 23))
        self.pushButton_browse.setMaximumSize(QtCore.QSize(25, 16777215))
        self.pushButton_browse.setObjectName("pushButton_browse")
        self.tabWidget.addTab(self.tab_4, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton_cancel = QtWidgets.QPushButton(Dialog)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.horizontalLayout.addWidget(self.pushButton_cancel)
        self.pushButton_save = QtWidgets.QPushButton(Dialog)
        self.pushButton_save.setObjectName("pushButton_save")
        self.horizontalLayout.addWidget(self.pushButton_save)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.checkBox_average_bursts.setText(_translate("Dialog", "Average Bursts (recommended)"))
        self.label_2.setText(_translate("Dialog", "Output file type:"))
        self.radioButton_csv.setText(_translate("Dialog", "Comma Seperated Value (.csv)"))
        self.radioButton_hdf5.setText(_translate("Dialog", "Hierarchical Data Format (.hdf5)"))
        self.label.setText(_translate("Dialog", "Split output files every:"))
        self.comboBox_split.setItemText(0, _translate("Dialog", "Do not split output files"))
        self.comboBox_split.setItemText(1, _translate("Dialog", "10 MB"))
        self.comboBox_split.setItemText(2, _translate("Dialog", "20 MB"))
        self.comboBox_split.setItemText(3, _translate("Dialog", "50 MB"))
        self.comboBox_split.setItemText(4, _translate("Dialog", "100 MB"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Output"))
        self.radioButton_posix_time.setToolTip(_translate("Dialog", "UTC (no time zone adjustment)"))
        self.radioButton_posix_time.setText(_translate("Dialog", "POSIX Time Stamp (seconds since Jan 1, 1970)"))
        self.radioButton_legacy_time.setText(_translate("Dialog", "Legacy (yyyy-mm-dd, HH:MM:SS.SSS)"))
        self.radioButton_iso8601_time.setText(_translate("Dialog", "ISO 8601 (yyyy-mm-ddTHH:MM:SS.SSS)"))
        self.radioButton_elapsed_time.setText(_translate("Dialog", "Elapsed Time (seconds)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Time"))
        self.radioButton_factory_cal.setText(_translate("Dialog", "Use Factory Calibration Values (Recommended)"))
        self.radioButton_custom_cal.setText(_translate("Dialog", "Use Custom Calibration File (Danger Zone)"))
        self.pushButton_browse.setText(_translate("Dialog", "..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Dialog", "Calibration Coefficients (advanced)"))
        self.pushButton_cancel.setText(_translate("Dialog", "Cancel"))
        self.pushButton_save.setText(_translate("Dialog", "Save"))

from . import icons_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

