# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer_files/setup.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(867, 1016)
        Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.gridLayout = QtWidgets.QGridLayout(Frame)
        self.gridLayout.setVerticalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton_scan = QtWidgets.QPushButton(Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_scan.sizePolicy().hasHeightForWidth())
        self.pushButton_scan.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_scan.setIcon(icon)
        self.pushButton_scan.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_scan.setFlat(True)
        self.pushButton_scan.setObjectName("pushButton_scan")
        self.horizontalLayout_5.addWidget(self.pushButton_scan)
        spacerItem = QtWidgets.QSpacerItem(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.horizontalLayout_5.setStretch(1, 1)
        self.gridLayout.addLayout(self.horizontalLayout_5, 0, 0, 1, 1)
        self.treeWidget = QtWidgets.QTreeWidget(Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeWidget.sizePolicy().hasHeightForWidth())
        self.treeWidget.setSizePolicy(sizePolicy)
        self.treeWidget.setMinimumSize(QtCore.QSize(200, 0))
        self.treeWidget.setMaximumSize(QtCore.QSize(200, 16777215))
        self.treeWidget.setIndentation(10)
        self.treeWidget.setObjectName("treeWidget")
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        self.treeWidget.header().setVisible(False)
        self.gridLayout.addWidget(self.treeWidget, 1, 0, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(Frame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 634, 949))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_10.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_10.setSpacing(0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_10.addItem(spacerItem1, 7, 1, 1, 2)
        self.frame_6 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_6.setObjectName("frame_6")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lineEdit_file_name = QtWidgets.QLineEdit(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_file_name.sizePolicy().hasHeightForWidth())
        self.lineEdit_file_name.setSizePolicy(sizePolicy)
        self.lineEdit_file_name.setMinimumSize(QtCore.QSize(200, 0))
        self.lineEdit_file_name.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lineEdit_file_name.setObjectName("lineEdit_file_name")
        self.gridLayout_3.addWidget(self.lineEdit_file_name, 2, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 2, 1, 1, 1)
        self.checkBox_led = QtWidgets.QCheckBox(self.frame_6)
        self.checkBox_led.setChecked(True)
        self.checkBox_led.setObjectName("checkBox_led")
        self.gridLayout_3.addWidget(self.checkBox_led, 2, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 1, 0, 1, 3)
        self.line_5 = QtWidgets.QFrame(self.frame_6)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout_3.addWidget(self.line_5, 0, 0, 1, 3)
        self.gridLayout_10.addWidget(self.frame_6, 1, 1, 1, 2)
        self.frame_3 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_6.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout_6.setObjectName("gridLayout_6")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem3, 3, 1, 1, 1)
        self.dateTimeEdit_start_time = QtWidgets.QDateTimeEdit(self.frame_3)
        self.dateTimeEdit_start_time.setEnabled(True)
        self.dateTimeEdit_start_time.setCalendarPopup(True)
        self.dateTimeEdit_start_time.setObjectName("dateTimeEdit_start_time")
        self.gridLayout_6.addWidget(self.dateTimeEdit_start_time, 4, 0, 1, 1)
        self.comboBox_start_time = QtWidgets.QComboBox(self.frame_3)
        self.comboBox_start_time.setObjectName("comboBox_start_time")
        self.comboBox_start_time.addItem("")
        self.comboBox_start_time.addItem("")
        self.gridLayout_6.addWidget(self.comboBox_start_time, 3, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_6.addWidget(self.label_4, 2, 0, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.frame_3)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_6.addWidget(self.line_3, 1, 0, 1, 2)
        self.gridLayout_6.setColumnStretch(0, 1)
        self.gridLayout_6.setColumnStretch(1, 1)
        self.gridLayout_10.addWidget(self.frame_3, 5, 1, 1, 2)
        self.frame_4 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_7.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.comboBox_end_time = QtWidgets.QComboBox(self.frame_4)
        self.comboBox_end_time.setObjectName("comboBox_end_time")
        self.comboBox_end_time.addItem("")
        self.comboBox_end_time.addItem("")
        self.gridLayout_7.addWidget(self.comboBox_end_time, 3, 0, 1, 1)
        self.dateTimeEdit_end_time = QtWidgets.QDateTimeEdit(self.frame_4)
        self.dateTimeEdit_end_time.setEnabled(True)
        self.dateTimeEdit_end_time.setCalendarPopup(True)
        self.dateTimeEdit_end_time.setObjectName("dateTimeEdit_end_time")
        self.gridLayout_7.addWidget(self.dateTimeEdit_end_time, 4, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem4, 4, 1, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.frame_4)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout_7.addWidget(self.line_4, 1, 0, 1, 2)
        self.label_9 = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout_7.addWidget(self.label_9, 2, 0, 1, 2)
        self.gridLayout_7.setColumnStretch(0, 1)
        self.gridLayout_7.setColumnStretch(1, 1)
        self.gridLayout_10.addWidget(self.frame_4, 6, 1, 1, 2)
        self.frame_pressure = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_pressure.setObjectName("frame_pressure")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.frame_pressure)
        self.gridLayout_9.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.line_6 = QtWidgets.QFrame(self.frame_pressure)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.gridLayout_9.addWidget(self.line_6, 2, 0, 1, 2)
        self.checkBox_pressure = QtWidgets.QCheckBox(self.frame_pressure)
        self.checkBox_pressure.setChecked(True)
        self.checkBox_pressure.setObjectName("checkBox_pressure")
        self.gridLayout_9.addWidget(self.checkBox_pressure, 5, 0, 1, 1)
        self.comboBox_pressure_burst_rate = QtWidgets.QComboBox(self.frame_pressure)
        self.comboBox_pressure_burst_rate.setObjectName("comboBox_pressure_burst_rate")
        self.gridLayout_9.addWidget(self.comboBox_pressure_burst_rate, 7, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.frame_pressure)
        self.label_11.setObjectName("label_11")
        self.gridLayout_9.addWidget(self.label_11, 7, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.frame_pressure)
        self.label_12.setObjectName("label_12")
        self.gridLayout_9.addWidget(self.label_12, 8, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.frame_pressure)
        self.label_13.setObjectName("label_13")
        self.gridLayout_9.addWidget(self.label_13, 6, 0, 1, 1)
        self.comboBox_pressure_interval = QtWidgets.QComboBox(self.frame_pressure)
        self.comboBox_pressure_interval.setObjectName("comboBox_pressure_interval")
        self.gridLayout_9.addWidget(self.comboBox_pressure_interval, 6, 1, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(15)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lineEdit_pressure_burst_duration = QtWidgets.QLineEdit(self.frame_pressure)
        self.lineEdit_pressure_burst_duration.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_pressure_burst_duration.sizePolicy().hasHeightForWidth())
        self.lineEdit_pressure_burst_duration.setSizePolicy(sizePolicy)
        self.lineEdit_pressure_burst_duration.setObjectName("lineEdit_pressure_burst_duration")
        self.horizontalLayout_4.addWidget(self.lineEdit_pressure_burst_duration)
        self.checkBox_continuous_2 = QtWidgets.QCheckBox(self.frame_pressure)
        self.checkBox_continuous_2.setObjectName("checkBox_continuous_2")
        self.horizontalLayout_4.addWidget(self.checkBox_continuous_2)
        self.gridLayout_9.addLayout(self.horizontalLayout_4, 8, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.frame_pressure)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.gridLayout_9.addWidget(self.label_14, 4, 0, 1, 1)
        self.gridLayout_9.setColumnStretch(0, 1)
        self.gridLayout_9.setColumnStretch(1, 1)
        self.gridLayout_10.addWidget(self.frame_pressure, 4, 1, 1, 1)
        self.frame_5 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_description = QtWidgets.QLabel(self.frame_5)
        self.label_description.setText("")
        self.label_description.setWordWrap(True)
        self.label_description.setObjectName("label_description")
        self.gridLayout_2.addWidget(self.label_description, 1, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 0, 0, 1, 1)
        self.gridLayout_10.addWidget(self.frame_5, 0, 1, 1, 1)
        self.frame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame.setObjectName("frame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_4.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 4, 0, 1, 1)
        self.checkBox_temperature = QtWidgets.QCheckBox(self.frame)
        self.checkBox_temperature.setChecked(True)
        self.checkBox_temperature.setObjectName("checkBox_temperature")
        self.gridLayout_4.addWidget(self.checkBox_temperature, 3, 0, 1, 2)
        self.line_2 = QtWidgets.QFrame(self.frame)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_4.addWidget(self.line_2, 1, 0, 1, 2)
        self.comboBox_temp_interval = QtWidgets.QComboBox(self.frame)
        self.comboBox_temp_interval.setObjectName("comboBox_temp_interval")
        self.gridLayout_4.addWidget(self.comboBox_temp_interval, 4, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 2, 0, 1, 2)
        self.gridLayout_4.setColumnStretch(0, 1)
        self.gridLayout_4.setColumnStretch(1, 1)
        self.gridLayout_10.addWidget(self.frame, 2, 1, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_5.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.line = QtWidgets.QFrame(self.frame_2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_5.addWidget(self.line, 2, 0, 1, 2)
        self.checkBox_accelerometer = QtWidgets.QCheckBox(self.frame_2)
        self.checkBox_accelerometer.setChecked(True)
        self.checkBox_accelerometer.setObjectName("checkBox_accelerometer")
        self.gridLayout_5.addWidget(self.checkBox_accelerometer, 5, 0, 1, 1)
        self.comboBox_orient_burst_rate = QtWidgets.QComboBox(self.frame_2)
        self.comboBox_orient_burst_rate.setObjectName("comboBox_orient_burst_rate")
        self.gridLayout_5.addWidget(self.comboBox_orient_burst_rate, 7, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_5.addWidget(self.label_6, 7, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.frame_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout_5.addWidget(self.label_8, 8, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.frame_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_5.addWidget(self.label_7, 6, 0, 1, 1)
        self.checkBox_magnetometer = QtWidgets.QCheckBox(self.frame_2)
        self.checkBox_magnetometer.setChecked(True)
        self.checkBox_magnetometer.setObjectName("checkBox_magnetometer")
        self.gridLayout_5.addWidget(self.checkBox_magnetometer, 5, 1, 1, 1)
        self.comboBox_orient_interval = QtWidgets.QComboBox(self.frame_2)
        self.comboBox_orient_interval.setObjectName("comboBox_orient_interval")
        self.gridLayout_5.addWidget(self.comboBox_orient_interval, 6, 1, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(15)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lineEdit_burst_duration = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_burst_duration.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_burst_duration.sizePolicy().hasHeightForWidth())
        self.lineEdit_burst_duration.setSizePolicy(sizePolicy)
        self.lineEdit_burst_duration.setObjectName("lineEdit_burst_duration")
        self.horizontalLayout_3.addWidget(self.lineEdit_burst_duration)
        self.checkBox_continuous = QtWidgets.QCheckBox(self.frame_2)
        self.checkBox_continuous.setObjectName("checkBox_continuous")
        self.horizontalLayout_3.addWidget(self.checkBox_continuous)
        self.gridLayout_5.addLayout(self.horizontalLayout_3, 8, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_5.addWidget(self.label_3, 4, 0, 1, 1)
        self.gridLayout_5.setColumnStretch(0, 1)
        self.gridLayout_5.setColumnStretch(1, 1)
        self.gridLayout_10.addWidget(self.frame_2, 3, 1, 1, 2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 1, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_unlock = QtWidgets.QPushButton(Frame)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/edit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_unlock.setIcon(icon1)
        self.pushButton_unlock.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_unlock.setFlat(True)
        self.pushButton_unlock.setObjectName("pushButton_unlock")
        self.horizontalLayout_2.addWidget(self.pushButton_unlock)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.pushButton_save = QtWidgets.QPushButton(Frame)
        self.pushButton_save.setMinimumSize(QtCore.QSize(125, 0))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_save.setIcon(icon2)
        self.pushButton_save.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_save.setFlat(True)
        self.pushButton_save.setObjectName("pushButton_save")
        self.horizontalLayout_2.addWidget(self.pushButton_save)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 1, 1, 1)
        self.gridLayout.setColumnStretch(1, 1)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.pushButton_scan.setText(_translate("Frame", "ID My Device"))
        self.treeWidget.headerItem().setText(0, _translate("Frame", "Column"))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, _translate("Frame", "Preset Configurations"))
        self.treeWidget.topLevelItem(0).child(0).setText(0, _translate("Frame", "Current Meter"))
        self.treeWidget.topLevelItem(0).child(0).child(0).setText(0, _translate("Frame", "Standard"))
        self.treeWidget.topLevelItem(0).child(0).child(1).setText(0, _translate("Frame", "Battery Saver"))
        self.treeWidget.topLevelItem(0).child(0).child(2).setText(0, _translate("Frame", "Energetic"))
        self.treeWidget.topLevelItem(0).child(1).setText(0, _translate("Frame", "Current Meter w/ Pressure"))
        self.treeWidget.topLevelItem(0).child(1).child(0).setText(0, _translate("Frame", "Standard"))
        self.treeWidget.topLevelItem(0).child(1).child(1).setText(0, _translate("Frame", "Battery Saver"))
        self.treeWidget.topLevelItem(0).child(1).child(2).setText(0, _translate("Frame", "Pressure Only"))
        self.treeWidget.topLevelItem(0).child(2).setText(0, _translate("Frame", "Data Logger"))
        self.treeWidget.topLevelItem(0).child(2).child(0).setText(0, _translate("Frame", "Orientation"))
        self.treeWidget.topLevelItem(0).child(2).child(1).setText(0, _translate("Frame", "Drop Detection"))
        self.treeWidget.topLevelItem(1).setText(0, _translate("Frame", "Advanced"))
        self.treeWidget.topLevelItem(1).child(0).setText(0, _translate("Frame", "New Custom Setup"))
        self.treeWidget.setSortingEnabled(__sortingEnabled)
        self.lineEdit_file_name.setToolTip(_translate("Frame", "This will be the filename of the datafile created by the logger"))
        self.checkBox_led.setText(_translate("Frame", "Blink LED when running"))
        self.label.setText(_translate("Frame", "Output Filename"))
        self.dateTimeEdit_start_time.setDisplayFormat(_translate("Frame", "yyyy-MM-dd HH:mm:ss"))
        self.comboBox_start_time.setItemText(0, _translate("Frame", "Start Recording Immediately"))
        self.comboBox_start_time.setItemText(1, _translate("Frame", "Start at Time (year-month-day hours:minutes:seconds)"))
        self.label_4.setText(_translate("Frame", "Start Time"))
        self.comboBox_end_time.setItemText(0, _translate("Frame", "Record Until Stopped"))
        self.comboBox_end_time.setItemText(1, _translate("Frame", "Stop at Time (year-month-day hours:minutes:seconds)"))
        self.dateTimeEdit_end_time.setDisplayFormat(_translate("Frame", "yyyy-MM-dd HH:mm:ss"))
        self.label_9.setText(_translate("Frame", "Stop Time"))
        self.checkBox_pressure.setText(_translate("Frame", "Pressure Sensor"))
        self.label_11.setText(_translate("Frame", "Burst Rate:"))
        self.label_12.setText(_translate("Frame", "Burst Duration (seconds):"))
        self.label_13.setText(_translate("Frame", "Burst Interval:"))
        self.checkBox_continuous_2.setText(_translate("Frame", "Continuous"))
        self.label_14.setText(_translate("Frame", "Pressure"))
        self.label_10.setText(_translate("Frame", "Description"))
        self.label_5.setText(_translate("Frame", "Sampling Interval:"))
        self.checkBox_temperature.setText(_translate("Frame", "Temperature"))
        self.label_2.setText(_translate("Frame", "Temperature"))
        self.checkBox_accelerometer.setText(_translate("Frame", "Accelerometer"))
        self.label_6.setText(_translate("Frame", "Burst Rate:"))
        self.label_8.setText(_translate("Frame", "Burst Duration (seconds):"))
        self.label_7.setText(_translate("Frame", "Burst Interval:"))
        self.checkBox_magnetometer.setText(_translate("Frame", "Magnetometer"))
        self.checkBox_continuous.setText(_translate("Frame", "Continuous"))
        self.label_3.setText(_translate("Frame", "Accelerometer/Magnetometer"))
        self.pushButton_unlock.setText(_translate("Frame", "Edit this Setup "))
        self.pushButton_save.setText(_translate("Frame", "Save Setup File "))

from . import icons_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Frame = QtWidgets.QFrame()
    ui = Ui_Frame()
    ui.setupUi(Frame)
    Frame.show()
    sys.exit(app.exec_())

